sudo: false

language: node_js
node_js:
  - 14.18.1

cache:
  directories:
    - node_modules

install:
  - npm install

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: $HEROKU_API_KEY
  app:
    master: example-ci-cd-22
    dev: example-ci-cd-22

