sudo: false

language: node_js
node_js:
  - 14.18.1
install:
  - npm install
script:
    - gem install dpl && gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=xxx --api-key=9d0c58ba-fd14-4df3-9592-e315928e1265
branches:
  only:
    - master
deploy:
  provider: heroku
  app:
    master: example-ci-cd-22
    dev: example-ci-cd-22
  api_key:
    secure: "9d0c58ba-fd14-4df3-9592-e315928e1265"

